#!/usr/bin/bash

sudo date

export LLVM_CONFIG=/usr/lib64/llvm21/bin/llvm-config
export CLANG=/usr/lib64/llvm21/bin/clang


PGUSER=$USERNAME
USE_FRESH_GIT=1
USE_GIT_CLEAN=1
USE_CONFIGURE=1
USE_MAKE_CLEAN=1
BRANCH=$1
ENABLE_CASSERT="--enable-cassert"
ENABLE_INJECTP=""
LOCALE_PROVIDER=""

if [[ "$1" = "--help" ]]; then

  echo "buildpgv [ --without-cassert ] [ {git branch} ]"
  exit 1

fi

if [[ "$1" = "--without-cassert" ]]; then
  BRANCH=$2
  ENABLE_CASSERT=""
fi

if [[ "$#" -eq 0 ]]; then

  BRANCH=""
  USE_FRESH_GIT=0
  USE_GIT_CLEAN=0
  USE_CONFIGURE=0
  USE_MAKE_CLEAN=0

fi

cd /home/pavel/src/postgresql/

case $BRANCH in
  "9.4")
    export GITBRANCH='REL9_4_STABLE'
    export PREFIX="/usr/local/pgsql/9.4"
    export PORT="5494"
    export STARTSCRIPTNAME="pgsql.94"
    export PSQLNAME="psql-9.4"
    ;;

  "9.5")
    export GITBRANCH='REL9_5_STABLE'
    export PREFIX="/usr/local/pgsql/9.5"
    export PORT="5495"
    export STARTSCRIPTNAME="pgsql.95"
    export PSQLNAME="psql-9.5"
    ;;

  "9.6")
    export GITBRANCH='REL9_6_STABLE'
    export PREFIX="/usr/local/pgsql/9.6"
    export PORT="5496"
    export STARTSCRIPTNAME="pgsql.96"
    export PSQLNAME="psql-9.6"
    ;;

  "10")
    export GITBRANCH='REL_10_STABLE'
    export PREFIX="/usr/local/pgsql/10"
    export PORT="5410"
    export STARTSCRIPTNAME="pgsql.10"
    export PSQLNAME="psql-10"
    ;;

  "11")
    export GITBRANCH='REL_11_STABLE'
    export PREFIX="/usr/local/pgsql/11"
    export PORT="5411"
    export STARTSCRIPTNAME="pgsql.11"
    export PSQLNAME="psql-11"
    ;;

  "12")
    export GITBRANCH='REL_12_STABLE'
    export PREFIX="/usr/local/pgsql/12"
    export PORT="5412"
    export STARTSCRIPTNAME="pgsql.12"
    export PSQLNAME="psql-12"
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "13")
    export GITBRANCH='REL_13_STABLE'
    export PREFIX="/usr/local/pgsql/13"
    export PORT="5413"
    export STARTSCRIPTNAME="pgsql.13"
    export PSQLNAME="psql-13"
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "14")
    export GITBRANCH='REL_14_STABLE'
    export PREFIX="/usr/local/pgsql/14"
    export PORT="5414"
    export STARTSCRIPTNAME="pgsql.14"
    export PSQLNAME="psql-14"
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "15")
    export GITBRANCH='REL_15_STABLE'
    export PREFIX="/usr/local/pgsql/15"
    export PORT="5415"
    export STARTSCRIPTNAME="pgsql.15"
    export PSQLNAME="psql-15"
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "15gd")
    export GITBRANCH='GoodData-15'
    export PREFIX="/usr/local/pgsql/15"
    export PORT="5415"
    export STARTSCRIPTNAME="pgsql.15"
    export PSQLNAME="psql-15"
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "16")
    export GITBRANCH='REL_16_STABLE'
    export PREFIX="/usr/local/pgsql/16"
    export PORT="5416"
    export STARTSCRIPTNAME="pgsql.16"
    export PSQLNAME="psql-16"
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "17")
    export GITBRANCH='REL_17_STABLE'
    export PREFIX="/usr/local/pgsql/17"
    export PORT="5417"
    export STARTSCRIPTNAME="pgsql.17"
    export PSQLNAME="psql-17"
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "18")
    export GITBRANCH='REL_18_STABLE'
    export PREFIX="/usr/local/pgsql/18"
    export PORT="5418"
    export STARTSCRIPTNAME="pgsql.18"
    export PSQLNAME="psql-18"
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    ;;

  "master")
    export GITBRANCH='master'
    export PREFIX="/usr/local/pgsql/master"
    export PORT="5432"
    export STARTSCRIPTNAME="pgsql.master"
    export PSQLNAME="psql"
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_LLVM="--with-llvm"
    export WITH_PYTHON="--with-python"
    export WITH_LIBXML="--with-libxml"
    export WITH_LIBURING="--with-liburing"
    export CFLAGS=" -Wimplicit-function-declaration -Wall -Wmissing-prototypes -Werror=return-type -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument"
    export ENABLE_INJECTP="--enable-injection-points"
    export LOCALE_PROVIDER="--locale-provider=icu --icu-locale=cs"
    ;;

  "current")
    export GITBRANCH=''
    export PREFIX="/usr/local/pgsql/master"
    export PORT="5432"
    export STARTSCRIPTNAME="pgsql.master"
    export PSQLNAME="psql"
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_FRESH_GIT=0
    export USE_GIT_CLEAN=0
    export USE_CONFIGURE=0
    export USE_MAKE_CLEAN=1
    export USE_LLVM="--with-llvm"
    export WITH_LIBXML="--with-libxml"
    export ENABLE_INJECTP="--enable-injection-points"
    ;;

  *)
    export GITBRANCH=$BRANCH
    export PREFIX="/usr/local/pgsql/master"
    export PORT="5432"
    export STARTSCRIPTNAME="pgsql.master"
    export PSQLNAME="psql"
    export USE_FRESH_GIT=0
    export USE_GIT_CLEAN=0
    export INITDBOPT='-c work_mem="64MB" -c shared_buffers="512MB"'
    export USE_LLVM="--with-llvm"
    export CFLAGS=" -Wimplicit-function-declaration -Wall -Wmissing-prototypes -Werror=return-type -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2"
    export CPPFLAGS="-DENFORCE_REGRESSION_TEST_NAME_RESTRICTIONS" # "-DRELCACHE_FORCE_RELEASE -DENFORCE_REGRESSION_TEST_NAME_RESTRICTIONS -DCATCACHE_FORCE_RELEASE"
    export WITH_LIBXML="--with-libxml"
    export WITH_LIBURING="--with-liburing"
    export ENABLE_INJECTP="--enable-injection-points"
    export LOCALE_PROVIDER="--locale-provider=icu --icu-locale=cs"
    ;;

esac

if [[ $USE_GIT_CLEAN -eq 1 ]]; then

  git stash

fi

if [[ "$GITBRANCH" != "" ]]; then

  git checkout $GITBRANCH

  if [[ $USE_GIT_CLEAN -eq 1 ]]; then

    git clean -f -x -d

  fi

  if [[ $USE_FRESH_GIT -eq 1 ]]; then

    git pull

  fi
fi

# export ASAN_OPTIONS=detect_leaks=0:abort_on_error=0:disable_coredump=0:strict_string_checks=1:check_initialization_order=1:strict_init_order=1::detect_stack_use_after_return=0
# export CPPFLAGS="-Og -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-sanitize=nonnull-attribute -fstack-protector" LDFLAGS='-fsanitize=address -fsanitize=undefined -static-libasan'


if [[ $USE_CONFIGURE -eq 1 ]]; then

  export CC="ccache gcc"
#  export CFLAGS=" -Wimplicit-function-declaration -Wall -Wmissing-prototypes -Werror=return-type -Wpointer-arith -Wdeclaration-after-statement  -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -Werror=suggest-attribute=format -Werror=char-subscripts"
#  export CFLAGS=" -Wimplicit-function-declaration -Wall -Wmissing-prototypes -Werror=return-type -Wpointer-arith -Wdeclaration-after-statement -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2"


./configure --enable-tap-tests --enable-debug  \
     --with-perl $WITH_PYTHON --prefix=$PREFIX $ENABLE_CASSERT --with-pgport=$PORT \
    --with-icu  --with-lz4 --with-tcl --enable-depend --with-zlib  --with-uuid=e2fs \
    $USE_LLVM --with-ssl=openssl $WITH_LIBXML $WITH_LIBURING $ENABLE_INJECTP --enable-tap-tests


#./configure --enable-tap-tests --enable-debug  \
#     --prefix=$PREFIX $ENABLE_CASSERT --with-pgport=$PORT \
#     $USE_LLVM   --enable-depend \
#  --with-ssl=openssl $WITH_LIBXML $WITH_LIBURING $ENABLE_INJECTP --enable-tap-tests



  if [[ $? -ne 0 ]]; then
	  exit 1
  fi
fi

if [[ $USE_MAKE_CLEAN -eq 1 ]]; then

make clean

fi

make all -j 3

if [[ $? -ne 0 ]]; then
	exit 1
fi

if [[ -f "/etc/init.d/$STARTSCRIPTNAME" ]]; then
  sudo /etc/init.d/$STARTSCRIPTNAME stop
fi

sudo rm -R -f "$PREFIX/include"
sudo make install

cd contrib
make -j 3
sudo make install
cd ..

cd doc
make

cd ..

sudo rm -R -f "$PREFIX/data"

sudo mkdir "$PREFIX/data"
sudo chown postgres:postgres "$PREFIX/data"
echo "$PREFIX/bin/initdb -D $PREFIX/data $LOCALE_PROVIDER  $INITDBOPT"
sudo su - postgres -c "$PREFIX/bin/initdb -D $PREFIX/data $LOCALE_PROVIDER  $INITDBOPT"
#sudo su - postgres -c "$PREFIX/bin/initdb -D $PREFIX/data $INITDBOPT"

if [[ $? -ne 0 ]]; then
	exit 1
fi

sudo rm -f $STARTSCRIPT

sudo cat contrib/start-scripts/linux | \
  sed "s+^prefix=/usr/local/pgsql+prefix=$PREFIX+" | \
  sed "s+^PGDATA=\"/usr/local/pgsql/data\"+PGDATA=$PREFIX/data+" > /tmp/$STARTSCRIPTNAME

sudo mv /tmp/$STARTSCRIPTNAME /etc/init.d
sudo chmod +x /etc/init.d/$STARTSCRIPTNAME

if [[ $? -ne 0 ]]; then
	exit 1
fi

sudo /etc/init.d/$STARTSCRIPTNAME start

until sudo su - postgres -c "$PREFIX/bin/pg_isready" ; do echo ; done
sudo su - postgres -c "$PREFIX/bin/psql -c \"create user $PGUSER login superuser\""

ln -f -s $PREFIX/bin/psql $HOME/bin/$PSQLNAME
