#!/usr/bin/bash

pgexttestv 9.5

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 9.6

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 10

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 11

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 12

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 13

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv master

if [[ $? -ne 0 ]]; then
  exit 1
fi
