#!/usr/bin/bash

pgexttestv 14

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 15

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 16

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 17

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv 18

if [[ $? -ne 0 ]]; then
  exit 1
fi

pgexttestv master

if [[ $? -ne 0 ]]; then
  exit 1
fi
